#!/bin/bash

if [ $# -ge 2 ]; then
    if [ $# -eq 3 ] && [ $2 -eq 1 ]; then
	cat "$1" | nc "$3" 4242
    fi

    if [ $2 -eq 0 ]; then
	nc -l 4242 > "$1"
    fi
else
    echo "./my_nc <file> <1:SEND|0:GET> [IP]"
fi
